namespace: mahdishariatzade
name: modules
version: 1.0.1
description: ماژول‌های سفارشی Ansible برای ویرایش SQLite و JSON و dns
authors:
  - mahdi-shariat <mahdishariat@outlook.com>
license: MIT
readme: README.md
repository: https://github.com/mahdishariatzade/ansible-modules
dependencies: {}
