name: Publish Ansible Collection to Galaxy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Adjust version for dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          # نسخه فعلی رو از galaxy.yml بخون
          CURRENT_VERSION=$(grep "version:" galaxy.yml | awk '{print $2}')
          # اضافه کردن پسوند -dev
          NEW_VERSION="${CURRENT_VERSION}-dev"
          # جایگزینی نسخه توی فایل
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" galaxy.yml
          echo "Updated version to $NEW_VERSION for dev branch"

      # 5. بیلد Collection
      - name: Build Ansible Collection
        run: ansible-galaxy collection build

      # 6. انتشار توی Ansible Galaxy
      - name: Publish to Galaxy
        env:
          GALAXY_API_TOKEN: ${{ secrets.GALAXY_API_TOKEN }}
        run: |
          ansible-galaxy collection publish *.tar.gz --token "$GALAXY_API_TOKEN"